version: "3.8"

services:
  mariadb:
    container_name: "mariadb"
    image: "mariadb:10"
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
    volumes:
      - ./.volumes/mysql/data:/var/lib/mysql/
      - ./.volumes/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
